#!/bin/bash

# delete old logstash indexes
/usr/local/bin/curator delete indices --time-unit days --older-than 7 --timestring '%Y.%m.%d' --prefix logstash

# delete old marvel indexes
/usr/local/bin/curator delete indices --time-unit days --older-than 7 --timestring '%Y.%m.%d' --prefix ".marvel" --exclude ".marvel-kibana"

# delete old snapshots
/usr/local/bin/curator delete snapshots --time-unit days --older-than 7 --repository clustermap-es-snapshots --timestring '%Y.%m.%d' --prefix "snapshot-"
